language: node_js
node_js:
- 8.9.4
script: NODE_ENV=production npm run coverage -- --maxWorkers=4
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - master
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}"
      - "<%{build_url}|#%{build_number}> - %{message}"
      - "Commit: \"%{commit_subject}\" by %{author}"
    secure: QbSz4R59yxzaS+6+xh8CyTdzwz8MpYi9FKeNPjxt1sAcFV/TgJvrHmwsGTJfjosHMT7ntEx7A9BSPP5vr4nnPEJKZY9axIYcQSQKkKX92g2zv+eYwJF8UoEySh3/gKoEFQZ+z1wQz82fnHxc59cdUD8b6i1wtqyxcS1B57TUYHnKQtgjzOMJtFqdirppDIenj27EYki91GAnQALIl8lhY1gPq1a1vIubius+B3dE3g4WJQz2ewRDK9MEZXzPvxaoaA8b2mFmz8vqTbEOZ8Wzl3fd2RXblE2EN6OyXCeUC2OW9Y9ifu0npgL52X0skVKppomUsZpKLrce1LzvZXS6AmO4HkzUdLojYhiZQ/aKUoAiNlD45eNgfKU6sf02+fto1nEHlTArLJfKYKjYAA564dNMCovnN9MZLzCtuJyTZveDdOPEGV9Q1CwQVkZ4PnDYzARwwaDFVhDhaRUG9XMuN6tak9onTfOdQJt342Ty3e9MmA1EpBtMYriDUeCbw2f6F/bvIJplqpy4cgMey4FUWOjP9Hk5f1X+F1YViZSaowOjY2sINbwsfFQMaSPd8eovLN3Ypj/ZyY5iO2bLbq4FV/sd6ZvZyQXE2GsioNkwTCYb0YIArdbJj/XNr6zIU/o0qWKgjZIlXW2EnJ1JZM3/oIhI7sDVbibObFNSCfYecRA=
